name: Check code quality

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - "LICENSE"
      - ".github/**"

jobs:
  Frontend-Quality:
    name: Frontend code quality
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout ğŸ›ï¸

      - uses: actions/setup-node@v3
        name: Setup Node âš™ï¸
        with:
          node-version: 18

      - name: Install dependencies ğŸ—ï¸
        run: npm install

      - name: Check code quality ğŸ”©
        run: npm run lint

  Rust-Quality:
    name: Rust code quality
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout ğŸ›ï¸

      - uses: actions-rs/toolchain@v1
        name: Install Rust toolchain â˜„ï¸
        with:
          toolchain: stable

      - uses: davidB/rust-cargo-make@v1
        name: Install cargo-make âŒ¨ï¸

      - uses: reinismu/clippy-check@master
        name: Check code quality ğŸ“‘
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          working-directory: src-tauri
