name: Build from current commit

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - "LICENSE"
      - ".github/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout ğŸ›ï¸

      - uses: actions/setup-node@v3
        name: Setup Node âš™ï¸
        with:
          node-version: 18

      - name: Install frontend dependencies ğŸ—ï¸
        run: npm install

      - uses: actions-rs/toolchain@v1
        name: Install Rust toolchain â˜„ï¸
        with:
          toolchain: stable

      - uses: davidB/rust-cargo-make@v1
        name: Install cargo-make âŒ¨ï¸

      - uses: ilammy/setup-nasm@v1
        name: Install NASM ğŸ–¥ï¸

      - name: Install build dependencies ğŸ›«
        run: |
          choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=User"'

      - name: Build app ğŸ› ï¸
        working-directory: src-tauri
        run: cargo make release

      - name: Upload artifacts â˜ï¸
        uses: actions/upload-artifact@v3
        with:
          name: nightly-build
          path: src-tauri/target/release/bundle/
          retention-days: 3
