name: Test code

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - "LICENSE"
      - ".github/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout ğŸ›ï¸

      - uses: actions/setup-node@v3
        name: Setup Node âš™ï¸
        with:
          node-version: 18

      - name: Install frontend dependencies ğŸ—ï¸
        run: npm install

      - name: Run frontend tests ğŸ§«
        run: npm test

      - uses: actions-rs/toolchain@v1
        name: Install Rust toolchain â˜„ï¸
        with:
          toolchain: stable

      - uses: davidB/rust-cargo-make@v1
        name: Install cargo-make âŒ¨ï¸

      - name: Run Rust code tests ğŸ§ª
        working-directory: src-tauri
        run: cargo make tests
